# Automatically generated by pb2py
# fmt: off
import protobuf as p
if __debug__:
    try:
        from typing import List
    except ImportError:
        List = None  # type: ignore


class RippleSignTx(p.MessageType):
    MESSAGE_WIRE_TYPE = 404
    FIELDS = {
        1: ('address_n', p.UVarintType, p.FLAG_REPEATED),
        2: ('account', p.UnicodeType, 0),
        3: ('fee', p.UVarintType, 0),
        4: ('flags', p.UVarintType, 0),
        5: ('sequence', p.UVarintType, 0),
        6: ('last_ledger_sequence', p.UVarintType, 0),
    }

    def __init__(
        self,
        address_n: List[int] = None,
        account: str = None,
        fee: int = None,
        flags: int = None,
        sequence: int = None,
        last_ledger_sequence: int = None,
    ) -> None:
        self.address_n = address_n if address_n is not None else []
        self.account = account
        self.fee = fee
        self.flags = flags
        self.sequence = sequence
        self.last_ledger_sequence = last_ledger_sequence
